import { _ } from 'meteor/underscore';
import { Meteor } from 'meteor/meteor';
import { Stuff, Movie, Drama, Action, Horror } from '../../api/stuff/stuff.js';

/*
import { Logger } from 'meteor/ostrio:logger';
import { LoggerConsole } from 'meteor/ostrio:loggerconsole';

const log = new Logger();
(new LoggerConsole(log)).enable(); */
/**
 * A list of Stuff to pre-fill the Collection.
 * @type {*[]}
 */
let dramaLim = 5,
  actionLim = dramaLim,
  horrorLim = dramaLim;


const stuffSeeds = [
  {
    Title: 'Wanted',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTQwNDM2MTMwMl5BMl5BanBnXkFtZTgwMjE4NjQxMTE@._V1_SX300.jpg',
    HomePoster: 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/m1.PNG?raw=true',
    Quantity: 100,
  },
  { Title: 'The Bourne Ultimatum',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNGNiNmU2YTMtZmU4OS00MjM0LTlmYWUtMjVlYjAzYjE2N2RjXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg',
    HomePoster: 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/m2.PNG?raw=true',
    Quantity: 100,
  },
  { Title: 'Guardians of the Galaxy Vol. 2',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTg2MzI1MTg3OF5BMl5BanBnXkFtZTgwNTU3NDA2MTI@._V1_SX300.jpg',
    HomePoster: 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/m3.PNG?raw=true',
    Quantity: 100,
  },
  { Title: 'National Treasure',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTY3NTc4OTYxMF5BMl5BanBnXkFtZTcwMjk5NzUyMw@@._V1_SX300.jpg',
    HomePoster: 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/m4.PNG?raw=true',
    Quantity: 100,
  },
  { Title: 'Bad Boys',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMGE1ZTQ0ZTEtZTEwZS00NWE0LTlmMDUtMTE1ZWJiZTYzZTQ2XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    HomePoster: 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/m5.PNG?raw=true',
    Quantity: 100,
  },
  { Title: 'Bright',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTcyNzk5NDg1Nl5BMl5BanBnXkFtZTgwNTM5MDQxNDM@._V1_SX300.jpg',
    HomePoster: 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/m6.PNG?raw=true',
    Quantity: 100,
  },
];
const movieList = [
  {
    Title: 'Deadpool 2',
    Year: '2018',
    Rated: 'R',
    Released: '18 May 2018',
    Runtime: '119 min',
    Genre: ['Action', 'Adventure', 'Comedy', 'Sci-Fi'],
    Director: 'David Leitch',
    Writer: 'Rhett Reese, Paul Wernick, Ryan Reynolds',
    Actors: 'Ryan Reynolds, Josh Brolin, Morena Baccarin, Julian Dennison',
    Plot: 'Foul-mouthed mutant mercenary Wade Wilson (AKA. Deadpool), brings together a team of fellow mutant rogues to protect a young boy with supernatural abilities from the brutal, time-traveling cyborg, Cable.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNjk1Njk3YjctMmMyYS00Y2I4LThhMzktN2U0MTMyZTFlYWQ5XkEyXkFqcGdeQXVyODM2ODEzMDA@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNjk1Njk3YjctMmMyYS00Y2I4LThhMzktN2U0MTMyZTFlYWQ5XkEyXkFqcGdeQXVyODM2ODEzMDA@._V1_SX300.jpg',
    imdbRating: '7.8',
    Quantity: 100,
  },
  {
    Title: 'Avengers: Infinity War',
    Year: '2018',
    Rated: 'PG-13',
    Released: '27 Apr 2018',
    Runtime: '149 min',
    Genre: ['Action', 'Adventure', 'Fantasy', 'Sci-Fi'],
    Director: 'Anthony Russo, Joe Russo',
    Writer: 'Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Joe Simon (Captain America created by), Jack Kirby (Captain America created by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Jim Starlin (Thanos,  Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Steve Englehart (Mantis created by), Don Heck (Mantis created by)',
    Actors: 'Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans',
    Plot: 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg',
    imdbRating: '8.5',
    Quantity: 100,
  }, {
    Title: 'The Cloverfield Paradox',
    Year: '2018',
    Rated: 'TV-MA',
    Released: '04 Feb 2018',
    Runtime: '102 min',
    Genre: ['Horror', 'Mystery', 'Sci-Fi', 'Thriller'],
    Director: 'Julius Onah',
    Writer: 'Oren Uziel (screenplay by), Oren Uziel (story by), Doug Jung (story by)',
    Actors: 'Gugu Mbatha-Raw, David Oyelowo, Daniel Brühl, John Ortiz',
    Plot: 'Orbiting a planet on the brink of war, scientists test a device to solve an energy crisis, and end up face-to-face with a dark alternate reality.',
    Language: 'English, Mandarin',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTAwOTIxMDA0MjZeQTJeQWpwZ15BbWU4MDg1MjgzNzQz._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTAwOTIxMDA0MjZeQTJeQWpwZ15BbWU4MDg1MjgzNzQz._V1_SX300.jpg',
    imdbRating: '5.6',
    Quantity: 100,
  }, {
    Title: 'The Predator',
    Year: '2018',
    Rated: 'N/A',
    Released: '14 Sep 2018',
    Runtime: '107 min',
    Genre: ['Action', 'Adventure', 'Horror', 'Sci-Fi', 'Thriller'],
    Director: 'Shane Black',
    Writer: 'Fred Dekker, Shane Black, Jim Thomas (based on characters created by), John Thomas (based on characters created by)',
    Actors: 'Boyd Holbrook, Trevante Rhodes, Jacob Tremblay, Keegan-Michael Key',
    Plot: "When a young boy accidentally triggers the universe's most lethal hunters' return to Earth, only a ragtag crew of ex-soldiers and a disgruntled scientist can prevent the end of the human race.",
    Language: 'English, Spanish',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjM5MDk2NDIxMF5BMl5BanBnXkFtZTgwNjU5NDk3NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjM5MDk2NDIxMF5BMl5BanBnXkFtZTgwNjU5NDk3NTM@._V1_SX300.jpg',
    imdbRating: '5.9',
    Quantity: 100,
  }, {
    Title: 'Proud Mary',
    Year: '2018',
    Rated: 'R',
    Released: '12 Jan 2018',
    Runtime: '89 min',
    Genre: ['Action', 'Crime', 'Thriller'],
    Director: 'Babak Najafi',
    Writer: 'John Stuart Newman (story by), Christian Swegal (story by), John Stuart Newman (screenplay by), Christian Swegal (screenplay by), Steve Antin (screenplay by)',
    Actors: "Taraji P. Henson, Billy Brown, Jahi Di'Allo Winston, Neal McDonough",
    Plot: 'Mary (Taraji P. Henson) is a hit woman working for an organized crime family in Boston, whose life is completely turned around when she meets a young boy whose path she crosses when a professional hit goes bad.',
    Language: 'English, Russian',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjA1MjI3MDU1MF5BMl5BanBnXkFtZTgwMjYwMTkxNDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjA1MjI3MDU1MF5BMl5BanBnXkFtZTgwMjYwMTkxNDM@._V1_SX300.jpg',
    imdbRating: '4.9',
    Quantity: 100,
  }, {
    Title: 'Slender Man',
    Year: '2018',
    Rated: 'PG-13',
    Released: '10 Aug 2018',
    Runtime: '93 min',
    Genre: ['Horror', 'Mystery', 'Thriller'],
    Director: 'Sylvain White',
    Writer: 'David Birke, Victor Surge (based on a character by)',
    Actors: 'Joey King, Julia Goldani Telles, Jaz Sinclair, Annalise Basso',
    Plot: "In a small town in Massachusetts, a group of friends, fascinated by the internet lore of the Slender Man, attempt to prove that he doesn't actually exist - until one of them mysteriously goes missing.",
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjE0MzcwMDAyNl5BMl5BanBnXkFtZTgwMzc4ODg0NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjE0MzcwMDAyNl5BMl5BanBnXkFtZTgwMzc4ODg0NDM@._V1_SX300.jpg',
    imdbRating: '3.2',
    Quantity: 100,
  }, {
    Title: 'Mortal Engines',
    Year: '2018',
    Rated: 'N/A',
    Released: '14 Dec 2018',
    Runtime: 'N/A',
    Genre: ['Action', 'Adventure', 'Fantasy', 'Sci-Fi', 'Thriller'],
    Director: 'Christian Rivers',
    Writer: 'Fran Walsh (screenplay by), Philippa Boyens (screenplay by), Peter Jackson (screenplay by), Philip Reeve (based on the book by)',
    Actors: 'Hugo Weaving, Stephen Lang, Hera Hilmar, Robert Sheehan',
    Plot: 'A mysterious young woman named Hester Shaw joins forces with Anna Fang, a dangerous outlaw with a bounty on her head, and Tom Natsworthy, an outcast from London, to lead a rebellion against a giant predator city on wheels.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzY1MDA2OTQ0N15BMl5BanBnXkFtZTgwMTkzNjU2NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNzY1MDA2OTQ0N15BMl5BanBnXkFtZTgwMTkzNjU2NTM@._V1_SX300.jpg',
    imdbRating: 'N/A',
    Quantity: 100,
  }, {
    Title: 'Escape Plan 2: Hades',
    Year: '2018',
    Rated: 'R',
    Released: '29 Jun 2018',
    Runtime: '96 min',
    Genre: ['Action', 'Thriller'],
    Director: 'Steven C. Miller',
    Writer: 'Miles Chapman, Miles Chapman (based on characters created by)',
    Actors: 'Sylvester Stallone, Dave Bautista, Xiaoming Huang, Jesse Metcalfe',
    Plot: 'Years after he fought his way out of an inescapable prison, Ray Breslin has organized a new top-notch security force. But when one of his team members goes missing, Breslin must return to the hell he once escaped from.',
    Language: 'English, Arabic',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTk4NjA0MjUyMF5BMl5BanBnXkFtZTgwMTEzNDQ1NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTk4NjA0MjUyMF5BMl5BanBnXkFtZTgwMTEzNDQ1NTM@._V1_SX300.jpg',
    imdbRating: '3.8',
    Quantity: 100,
  }, {
    Title: 'The Darkest Minds',
    Year: '2018',
    Rated: 'PG-13',
    Released: '03 Aug 2018',
    Runtime: '104 min',
    Genre: ['Sci-Fi', 'Thriller'],
    Director: 'Jennifer Yuh Nelson',
    Writer: 'Chad Hodge (screenplay by), Alexandra Bracken (based upon the novel by)',
    Actors: 'Amandla Stenberg, Mandy Moore, Bradley Whitford, Harris Dickinson',
    Plot: 'Imprisoned by an adult world that now fears everyone under 18, a group of teens form a resistance group to fight back and reclaim control of their future.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTUxOGE3OTUtM2I2My00YzE3LTg2NDktZTI3NjE4NDdjMGFiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTUxOGE3OTUtM2I2My00YzE3LTg2NDktZTI3NjE4NDdjMGFiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    imdbRating: '5.6',
    Quantity: 100,
  }, {
    Title: 'LEGO DC Comics Super Heroes: Aquaman - Rage of Atlantis',
    Year: '2018',
    Rated: 'NOT RATED',
    Released: '22 Jul 2018',
    Runtime: '77 min',
    Genre: ['Animation', 'Action', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Sci-Fi'],
    Director: 'Matt Peters',
    Writer: 'James Krieg, Jeremy Adams, Paul Norris (character created by: Aquaman), Marv Wolfman (character created by: Cyborg), George Pérez (character created by: Cyborg), William Moulton Marston (character created by: Wonder Woman), Roger Slifer (character created by: Lobo), Keith Giffen (character created by: Lobo)',
    Actors: 'Jonathan Adams, Dee Bradley Baker, Troy Baker, Eric Bauza',
    Plot: 'Aquaman must battle foes in the air, on land and in the depths of the Seven Seas, along with some help from The Justice League, to save the day .',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMzQyMjQ5YTUtNWY3Ni00NjZkLWExMmUtYTliYWRlNDIyZmJkXkEyXkFqcGdeQXVyNTM3MDMyMDQ@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMzQyMjQ5YTUtNWY3Ni00NjZkLWExMmUtYTliYWRlNDIyZmJkXkEyXkFqcGdeQXVyNTM3MDMyMDQ@._V1_SX300.jpg',
    imdbRating: '5.8',
    Quantity: 100,
  }, {
    Title: 'Mamma Mia! Here We Go Again',
    Year: '2018',
    Rated: 'PG-13',
    Released: '20 Jul 2018',
    Runtime: '114 min',
    Genre: ['Comedy', 'Musical', 'Romance'],
    Director: 'Ol Parker',
    Writer: 'Ol Parker, Richard Curtis (story by), Ol Parker (story by), Catherine Johnson (story by), Catherine Johnson (based on the original musical by), Judy Craymer (originally conceived by), ABBA (based on the songs of)',
    Actors: 'Amanda Seyfried, Andy Garcia, Celia Imrie, Lily James',
    Plot: "Five years after the events of Mamma Mia! (2008), Sophie prepares for the grand reopening of the Hotel Bella Donna as she learns more about her mother's past.",
    Language: 'English, French, Greek',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjEwMTM3OTI1NV5BMl5BanBnXkFtZTgwNDk5NTY0NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjEwMTM3OTI1NV5BMl5BanBnXkFtZTgwNDk5NTY0NTM@._V1_SX300.jpg',
    imdbRating: '7.0',
    Quantity: 100,
  }, {
    Title: 'Isle of Dogs',
    Year: '2018',
    Rated: 'PG-13',
    Released: '13 Apr 2018',
    Runtime: '101 min',
    Genre: ['Animation', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Sci-Fi'],
    Director: 'Wes Anderson',
    Writer: 'Wes Anderson (story by), Roman Coppola (story by), Jason Schwartzman (story by), Kunichi Nomura (story by), Wes Anderson (screenplay by)',
    Actors: 'Bryan Cranston, Koyu Rankin, Edward Norton, Bob Balaban',
    Plot: "Set in Japan, Isle of Dogs follows a boy's odyssey in search of his lost dog.",
    Language: 'English, Japanese',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTYyOTUwNjAxM15BMl5BanBnXkFtZTgwODcyMzE0NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTYyOTUwNjAxM15BMl5BanBnXkFtZTgwODcyMzE0NDM@._V1_SX300.jpg',
    imdbRating: '8.0',
    Quantity: 100,
  }, {
    Title: 'The Grinch',
    Year: '2018',
    Rated: 'N/A',
    Released: '09 Nov 2018',
    Runtime: '86 min',
    Genre: ['Animation', 'Comedy', 'Family', 'Fantasy'],
    Director: 'Yarrow Cheney, Scott Mosier',
    Writer: 'Michael LeSieur (screenplay by), Tommy Swerdlow (screenplay by), Dr. Seuss (based on the book "How The Grinch Stole Christmas" by)',
    Actors: 'Benedict Cumberbatch, Cameron Seely, Rashida Jones, Pharrell Williams',
    Plot: 'A grumpy Grinch plots to ruin Christmas for the village of Whoville.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYmE5Yjg0MzktYzgzMi00YTFiLWJjYTItY2M5MmI1ODI4MDY3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BYmE5Yjg0MzktYzgzMi00YTFiLWJjYTItY2M5MmI1ODI4MDY3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    imdbRating: '6.3',
    Quantity: 100,
  }, {
    Title: 'Anon',
    Year: '2018',
    Rated: 'TV-MA',
    Released: '04 May 2018',
    Runtime: '100 min',
    Genre: ['Crime', 'Mystery', 'Sci-Fi', 'Thriller'],
    Director: 'Andrew Niccol',
    Writer: 'Andrew Niccol',
    Actors: 'Clive Owen, Afiya Bennett, Morgan Allen, Jeffrey Men',
    Plot: 'In a world without anonymity or crime, a detective meets a woman who threatens their security.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjE0MjIwMDE2MV5BMl5BanBnXkFtZTgwMzM5MDQzNTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjE0MjIwMDE2MV5BMl5BanBnXkFtZTgwMzM5MDQzNTM@._V1_SX300.jpg',
    imdbRating: '6.1',
    Quantity: 100,
  }, {
    Title: 'The Nun',
    Year: '2018',
    Rated: 'R',
    Released: '07 Sep 2018',
    Runtime: '96 min',
    Genre: ['Horror', 'Mystery', 'Thriller'],
    Director: 'Corin Hardy',
    Writer: 'Gary Dauberman (screenplay by), James Wan (story by), Gary Dauberman (story by)',
    Actors: 'Demián Bichir, Taissa Farmiga, Jonas Bloquet, Bonnie Aarons',
    Plot: 'A priest with a haunted past and a novice on the threshold of her final vows are sent by the Vatican to investigate the death of a young nun in Romania and confront a malevolent force in the form of a demonic nun.',
    Language: 'English, French, Romanian, Latin',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjEwMDE1NzI3M15BMl5BanBnXkFtZTgwNjg2NjExNjM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjEwMDE1NzI3M15BMl5BanBnXkFtZTgwNjg2NjExNjM@._V1_SX300.jpg',
    imdbRating: '5.6',
    Quantity: 100,
  }, {
    Title: 'Bohemian Rhapsody',
    Year: '2018',
    Rated: 'N/A',
    Released: '02 Nov 2018',
    Runtime: '134 min',
    Genre: ['Biography', 'Drama', 'Music'],
    Director: 'Bryan Singer',
    Writer: 'Anthony McCarten (story by), Peter Morgan (story by), Anthony McCarten (screenplay by)',
    Actors: 'Rami Malek, Lucy Boynton, Gwilym Lee, Ben Hardy',
    Plot: "A chronicle of the years leading up to Queen's legendary appearance at the Live Aid (1985) concert.",
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNDg2NjIxMDUyNF5BMl5BanBnXkFtZTgwMzEzNTE1NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNDg2NjIxMDUyNF5BMl5BanBnXkFtZTgwMzEzNTE1NTM@._V1_SX300.jpg',
    imdbRating: '8.4',
    Quantity: 100,
  }, {
    Title: '7 Days in Entebbe',
    Year: '2018',
    Rated: 'PG-13',
    Released: '16 Mar 2018',
    Runtime: '107 min',
    Genre: ['Action', 'Crime', 'Drama', 'History', 'Thriller'],
    Director: 'José Padilha',
    Writer: 'Gregory Burke (screenplay by)',
    Actors: 'Batsheva Dance Company, Zina Zinchenko, Ben Schnetzer, Daniel Brühl',
    Plot: 'Inspired by the true events of the 1976 hijacking of an Air France flight en route from Tel Aviv to Paris, and the most daring rescue mission ever attempted.',
    Language: 'English, German, French, Hebrew, Arabic',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjAwNDMzNzg0Nl5BMl5BanBnXkFtZTgwOTkxNjY2NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjAwNDMzNzg0Nl5BMl5BanBnXkFtZTgwOTkxNjY2NDM@._V1_SX300.jpg',
    imdbRating: '5.8',
    Quantity: 100,
  }, {
    Title: 'Pacific Rim: Uprising',
    Year: '2018',
    Rated: 'PG-13',
    Released: '23 Mar 2018',
    Runtime: '111 min',
    Genre: ['Action', 'Adventure', 'Sci-Fi'],
    Director: 'Steven S. DeKnight',
    Writer: 'Steven S. DeKnight, Emily Carmichael, Kira Snyder, T.S. Nowlin, Travis Beacham (based on characters created by)',
    Actors: 'John Boyega, Scott Eastwood, Cailee Spaeny, Burn Gorman',
    Plot: 'Jake Pentecost, son of Stacker Pentecost, reunites with Mako Mori to lead a new generation of Jaeger pilots, including rival Lambert and 15-year-old hacker Amara, against a new Kaiju threat.',
    Language: 'English, Mandarin, Russian',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjI3Nzg0MTM5NF5BMl5BanBnXkFtZTgwOTE2MTgwNTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjI3Nzg0MTM5NF5BMl5BanBnXkFtZTgwOTE2MTgwNTM@._V1_SX300.jpg',
    imdbRating: '5.7',
    Quantity: 100,
  }, {
    Title: 'Den of Thieves',
    Year: '2018',
    Rated: 'R',
    Released: '19 Jan 2018',
    Runtime: '140 min',
    Genre: ['Action', 'Crime', 'Drama', 'Mystery', 'Thriller'],
    Director: 'Christian Gudegast',
    Writer: 'Christian Gudegast (screenplay by), Christian Gudegast (story by), Paul Scheuring (story by)',
    Actors: "Gerard Butler, Pablo Schreiber, O'Shea Jackson Jr., 50 Cent",
    Plot: "A gritty crime saga which follows the lives of an elite unit of the LA County Sheriff's Dept. and the state's most successful bank robbery crew as the outlaws plan a seemingly impossible heist on the Federal Reserve Bank.",
    Language: 'English, Polynesian',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMzYyODcwMDAyM15BMl5BanBnXkFtZTgwOTA4MjIwNDI@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMzYyODcwMDAyM15BMl5BanBnXkFtZTgwOTA4MjIwNDI@._V1_SX300.jpg',
    imdbRating: '7.0',
    Quantity: 100,
  }, {
    Title: 'Johnny English Strikes Again',
    Year: '2018',
    Rated: 'PG',
    Released: '26 Oct 2018',
    Runtime: '89 min',
    Genre: ['Action', 'Adventure', 'Comedy'],
    Director: 'David Kerr',
    Writer: 'William Davies (screenplay by)',
    Actors: 'Kevin Eldon, Emma Thompson, Adam James, Rowan Atkinson',
    Plot: 'After a cyber-attack reveals the identity of all of the active undercover agents in Britain, Johnny English is forced to come out of retirement to find the mastermind hacker.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjI4MjQ3MjI5MV5BMl5BanBnXkFtZTgwNjczMDE4NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjI4MjQ3MjI5MV5BMl5BanBnXkFtZTgwNjczMDE4NTM@._V1_SX300.jpg',
    imdbRating: '6.6',
    Quantity: 100,
  }, {
    Title: 'BlacKkKlansman',
    Year: '2018',
    Rated: 'R',
    Released: '10 Aug 2018',
    Runtime: '135 min',
    Genre: ['Biography', 'Comedy', 'Crime', 'Drama'],
    Director: 'Spike Lee',
    Writer: 'Charlie Wachtel, David Rabinowitz, Kevin Willmott, Spike Lee, Ron Stallworth (based on the book by)',
    Actors: 'Alec Baldwin, John David Washington, Isiah Whitlock Jr., Robert John Burke',
    Plot: 'Ron Stallworth, an African American police officer from Colorado Springs, CO, successfully manages to infiltrate the local Ku Klux Klan branch with the help of a Jewish surrogate who eventually becomes its leader. Based on actual events.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjUyOTE1NjI0OF5BMl5BanBnXkFtZTgwMTM4ODQ5NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjUyOTE1NjI0OF5BMl5BanBnXkFtZTgwMTM4ODQ5NTM@._V1_SX300.jpg',
    imdbRating: '7.6',
    Quantity: 100,
  }, {
    Title: 'Red Sparrow',
    Year: '2018',
    Rated: 'R',
    Released: '02 Mar 2018',
    Runtime: '140 min',
    Genre: ['Action', 'Drama', 'Thriller'],
    Director: 'Francis Lawrence',
    Writer: 'Justin Haythe (screenplay by), Jason Matthews (based upon the book by)',
    Actors: 'Jennifer Lawrence, Joel Edgerton, Matthias Schoenaerts, Charlotte Rampling',
    Plot: "Ballerina Dominika Egorova is recruited to 'Sparrow School,' a Russian intelligence service where she is forced to use her body as a weapon. Her first mission, targeting a C.I.A. agent, threatens to unravel the security of both nations.",
    Language: 'English, Russian',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTA3MDkxOTc4NDdeQTJeQWpwZ15BbWU4MDAxNzgyNTQz._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTA3MDkxOTc4NDdeQTJeQWpwZ15BbWU4MDAxNzgyNTQz._V1_SX300.jpg',
    imdbRating: '6.6',
    Quantity: 100,
  }, {
    Title: 'Solo: A Star Wars Story',
    Year: '2018',
    Rated: 'PG-13',
    Released: '25 May 2018',
    Runtime: '135 min',
    Genre: ['Action', 'Adventure', 'Fantasy', 'Sci-Fi'],
    Director: 'Ron Howard',
    Writer: 'Jonathan Kasdan, Lawrence Kasdan, George Lucas (based on characters created by)',
    Actors: 'Alden Ehrenreich, Joonas Suotamo, Woody Harrelson, Emilia Clarke',
    Plot: 'During an adventure into the criminal underworld, Han Solo meets his future co-pilot Chewbacca and encounters Lando Calrissian years before joining the Rebellion.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BOTM2NTI3NTc3Nl5BMl5BanBnXkFtZTgwNzM1OTQyNTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BOTM2NTI3NTc3Nl5BMl5BanBnXkFtZTgwNzM1OTQyNTM@._V1_SX300.jpg',
    imdbRating: '7.0',
    Quantity: 100,
  }, {
    Title: 'First Man',
    Year: '2018',
    Rated: 'N/A',
    Released: '12 Oct 2018',
    Runtime: '141 min',
    Genre: ['Biography', 'Drama', 'History'],
    Director: 'Damien Chazelle',
    Writer: 'Josh Singer (screenplay by), James R. Hansen (based on the book by)',
    Actors: 'Ryan Gosling, Claire Foy, Jason Clarke, Kyle Chandler',
    Plot: 'A look at the life of the astronaut, Neil Armstrong, and the legendary space mission that led him to become the first man to walk on the Moon on July 20, 1969.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMDBhOTMxN2UtYjllYS00NWNiLWE1MzAtZjg3NmExODliMDQ0XkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMDBhOTMxN2UtYjllYS00NWNiLWE1MzAtZjg3NmExODliMDQ0XkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg',
    imdbRating: '7.7',
    Quantity: 100,
  }, {
    Title: 'Fifty Shades Freed',
    Year: '2018',
    Rated: 'R',
    Released: '09 Feb 2018',
    Runtime: '105 min',
    Genre: ['Drama', 'Romance', 'Thriller'],
    Director: 'James Foley',
    Writer: 'Niall Leonard (screenplay by), E.L. James (based on the novel by)',
    Actors: 'Dakota Johnson, Jamie Dornan, Eric Johnson, Eloise Mumford',
    Plot: 'Anastasia and Christian get married, but Jack Hyde continues to threaten their relationship.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTYxOTQ1MzI0Nl5BMl5BanBnXkFtZTgwMzgwMzIxNDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTYxOTQ1MzI0Nl5BMl5BanBnXkFtZTgwMzgwMzIxNDM@._V1_SX300.jpg',
    imdbRating: '4.5',
    Quantity: 100,
  }, {
    Title: 'Hotel Transylvania 3: Summer Vacation',
    Year: '2018',
    Rated: 'PG',
    Released: '13 Jul 2018',
    Runtime: '97 min',
    Genre: ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy'],
    Director: 'Genndy Tartakovsky',
    Writer: 'Michael McCullers, Genndy Tartakovsky, Todd Durham (based on characters created by)',
    Actors: 'Adam Sandler, Andy Samberg, Selena Gomez, Kevin James',
    Plot: 'Count Dracula and company participate in a cruise for sea-loving monsters, unaware that their boat is being commandeered by the monster-hating Van Helsing family.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNjA1MzU5MTY3OF5BMl5BanBnXkFtZTgwNTU5MDA3NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNjA1MzU5MTY3OF5BMl5BanBnXkFtZTgwNTU5MDA3NTM@._V1_SX300.jpg',
    imdbRating: '6.3',
    Quantity: 100,
  }, {
    Title: 'Early Man',
    Year: '2018',
    Rated: 'PG',
    Released: '16 Feb 2018',
    Runtime: '89 min',
    Genre: ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Sport'],
    Director: 'Nick Park',
    Writer: 'Mark Burton (screenplay by), James Higginson (screenplay by), Mark Burton (story by), Nick Park (story by)',
    Actors: 'Eddie Redmayne, Tom Hiddleston, Maisie Williams, Timothy Spall',
    Plot: 'Set at the dawn of time, when prehistoric creatures and woolly mammoths roamed the earth, Early Man tells the story of Dug, along with sidekick Hognob as they unite his tribe against a mighty enemy Lord Nooth and his Bronze Age City to save their home.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYWMxYWVjNzAtMTY0YS00YWQyLWExMGItMjUxODkwYzQyNzMwXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BYWMxYWVjNzAtMTY0YS00YWQyLWExMGItMjUxODkwYzQyNzMwXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg',
    imdbRating: '6.1',
    Quantity: 100,
  }, {
    Title: 'Spider-Man: Into the Spider-Verse',
    Year: '2018',
    Rated: 'N/A',
    Released: '14 Dec 2018',
    Runtime: 'N/A',
    Genre: ['Animation', 'Action', 'Adventure', 'Sci-Fi'],
    Director: 'Bob Persichetti, Peter Ramsey, Rodney Rothman',
    Writer: 'Phil Lord (screenplay by), Steve Ditko (Spider-Man created by), David Hine (comic characters created by), Stan Lee (Spider-Man created by), Rodney Rothman (screenplay by), Brian Michael Bendis (Miles Morales created by), Fabrice Sapolsky (comic characters created by), Sara Pichelli (Miles Morales created by)',
    Actors: 'Hailee Steinfeld, Liev Schreiber, Nicolas Cage, Mahershala Ali',
    Plot: 'Spider-Man crosses parallel dimensions and teams up with the Spider-Men of those dimensions to stop a threat to all reality.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjMzMzQ0NzI5Nl5BMl5BanBnXkFtZTgwNjc2NTY0NjM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjMzMzQ0NzI5Nl5BMl5BanBnXkFtZTgwNjc2NTY0NjM@._V1_SX300.jpg',
    imdbRating: 'N/A',
    Quantity: 100,
  }, {
    Title: 'Maze Runner: The Death Cure',
    Year: '2018',
    Rated: 'PG-13',
    Released: '26 Jan 2018',
    Runtime: '143 min',
    Genre: ['Action', 'Sci-Fi', 'Thriller'],
    Director: 'Wes Ball',
    Writer: 'T.S. Nowlin (screenplay by), James Dashner (based upon the novel by)',
    Actors: "Dylan O'Brien, Ki Hong Lee, Kaya Scodelario, Thomas Brodie-Sangster",
    Plot: 'Young hero Thomas embarks on a mission to find a cure for a deadly disease known as "The Flare".',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTYyNzk3MDc2NF5BMl5BanBnXkFtZTgwMDk3OTM1NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTYyNzk3MDc2NF5BMl5BanBnXkFtZTgwMDk3OTM1NDM@._V1_SX300.jpg',
    imdbRating: '6.3',
    Quantity: 100,
  }, {
    Title: 'Sirens & Serenity',
    Year: '2018',
    Rated: 'N/A',
    Released: 'N/A',
    Runtime: 'N/A',
    Genre: ['Short', 'Action', 'Drama', 'Fantasy'],
    Director: 'Matthew David, Eliot Gurrin, Olia Oparina, Todd Zing',
    Writer: 'Peter Kent, Todd Zing (created by), Todd Zing',
    Actors: 'Danni Spring, Todd Zing, Jisaura Cardinale, Sierra Renfro',
    Plot: 'On the verge of a creative epiphany, a street musician struggles to follow his muse while contending with three sirens hell-bent on seducing and destroying him.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BZmQ0YTAwYjEtNjQyMy00NGMyLThkZDQtM2M3YThmM2I2NzQ3XkEyXkFqcGdeQXVyNTQzODA0Nzk@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BZmQ0YTAwYjEtNjQyMy00NGMyLThkZDQtM2M3YThmM2I2NzQ3XkEyXkFqcGdeQXVyNTQzODA0Nzk@._V1_SX300.jpg',
    imdbRating: 'N/A',
    Quantity: 100,
  }, {
    Title: 'Overboard',
    Year: '2018',
    Rated: 'PG-13',
    Released: '04 May 2018',
    Runtime: '112 min',
    Genre: ['Comedy', 'Romance'],
    Director: 'Rob Greenberg',
    Writer: 'Bob Fisher (screenplay by), Rob Greenberg (screenplay by), Leslie Dixon (screenplay by), Leslie Dixon (story by)',
    Actors: 'Eugenio Derbez, Anna Faris, Eva Longoria, John Hannah',
    Plot: 'A spoiled, wealthy yacht owner is thrown overboard and becomes the target of revenge from his mistreated employee.',
    Language: 'English, Norwegian, Spanish, French',
    Poster: 'https://m.media-amazon.com/images/M/MV5BM2E5MWYwYTktMmIxZC00MWVkLTk4YjctNGU1OGVjMDIwNzM2XkEyXkFqcGdeQXVyNTAwODk1NzY@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BM2E5MWYwYTktMmIxZC00MWVkLTk4YjctNGU1OGVjMDIwNzM2XkEyXkFqcGdeQXVyNTAwODk1NzY@._V1_SX300.jpg',
    imdbRating: '5.9',
    Quantity: 100,
  }, {
    Title: 'Game Night',
    Year: '2018',
    Rated: 'R',
    Released: '23 Feb 2018',
    Runtime: '100 min',
    Genre: ['Action', 'Comedy', 'Crime', 'Mystery'],
    Director: 'John Francis Daley, Jonathan Goldstein',
    Writer: 'Mark Perez',
    Actors: 'Jason Bateman, Rachel McAdams, Kyle Chandler, Sharon Horgan',
    Plot: 'A group of friends who meet regularly for game nights find themselves entangled in a real-life mystery when the shady brother of one of them is seemingly kidnapped by dangerous gangsters.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjI3ODkzNDk5MF5BMl5BanBnXkFtZTgwNTEyNjY2NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjI3ODkzNDk5MF5BMl5BanBnXkFtZTgwNTEyNjY2NDM@._V1_SX300.jpg',
    imdbRating: '7.0',
    Quantity: 100,
  }, {
    Title: 'Acts of Violence',
    Year: '2018',
    Rated: 'R',
    Released: '12 Jan 2018',
    Runtime: '86 min',
    Genre: ['Action', 'Crime'],
    Director: 'Brett Donowho',
    Writer: 'Nicolas Aaron Mezzanatto (screen play by)',
    Actors: 'Bruce Willis, Cole Hauser, Shawn Ashmore, Ashton Holmes',
    Plot: 'When his fiancee is kidnapped by human traffickers, Roman (Ashton Holmes) and his ex-military brothers set out to track her down and save her before it is too late. Along the way, Roman ...',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjM3NzI1NDMyNl5BMl5BanBnXkFtZTgwNzUyMDgzNDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjM3NzI1NDMyNl5BMl5BanBnXkFtZTgwNzUyMDgzNDM@._V1_SX300.jpg',
    imdbRating: '5.2',
    Quantity: 100,
  }, {
    Title: 'Father of the Year',
    Year: '2018',
    Rated: 'TV-14',
    Released: '20 Jul 2018',
    Runtime: '94 min',
    Genre: ['Comedy'],
    Director: 'Tyler Spindel',
    Writer: 'Brandon Cournoyer, Tyler Spindel',
    Actors: 'David Spade, Nat Faxon, Joey Bragg, Matt Shively',
    Plot: "Before NYC, college valedictorian Ben visits his trailer park loser dad. Same evening Ben argues with Larry about whose dad can kick the other dad's ass. Loser dad hears of this and tries to beat up doormat dad and chaos follows.",
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNTMzNjE4NjE2MV5BMl5BanBnXkFtZTgwOTc1NjE4NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNTMzNjE4NjE2MV5BMl5BanBnXkFtZTgwOTc1NjE4NTM@._V1_SX300.jpg',
    imdbRating: '5.2',
    Quantity: 100,
  }, {
    Title: 'Mile 22',
    Year: '2018',
    Rated: 'R',
    Released: '17 Aug 2018',
    Runtime: '94 min',
    Genre: ['Action', 'Adventure', 'Crime', 'Thriller'],
    Director: 'Peter Berg',
    Writer: 'Lea Carpenter (screenplay by), Graham Roland (story by), Lea Carpenter (story by)',
    Actors: 'Mark Wahlberg, Lauren Cohan, Iko Uwais, John Malkovich',
    Plot: 'An elite American intelligence officer, aided by a top-secret tactical command unit, tries to smuggle a mysterious police officer with sensitive information out of Indonesia.',
    Language: 'English, Russian, Indonesian',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzUyODk4OTkxNF5BMl5BanBnXkFtZTgwMzY0MDgzNTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNzUyODk4OTkxNF5BMl5BanBnXkFtZTgwMzY0MDgzNTM@._V1_SX300.jpg',
    imdbRating: '6.1',
    Quantity: 100,
  }, {
    Title: 'Alpha',
    Year: '2018',
    Rated: 'PG-13',
    Released: '17 Aug 2018',
    Runtime: '96 min',
    Genre: ['Adventure', 'Drama', 'Family'],
    Director: 'Albert Hughes',
    Writer: 'Daniele Sebastian Wiedenhaupt (screenplay by), Albert Hughes (story by)',
    Actors: 'Kodi Smit-McPhee, Jóhannes Haukur Jóhannesson, Marcin Kowalczyk, Jens Hultén',
    Plot: 'In the prehistoric past, a young man struggles to return home after being separated from his tribe during a buffalo hunt. He finds a similarly lost wolf companion and starts a friendship that would change humanity.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BODI4OTk1ODY3N15BMl5BanBnXkFtZTgwMDI1MTcwNjM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BODI4OTk1ODY3N15BMl5BanBnXkFtZTgwMDI1MTcwNjM@._V1_SX300.jpg',
    imdbRating: '6.8',
    Quantity: 100,
  }, {
    Title: 'Jurassic World: Fallen Kingdom',
    Year: '2018',
    Rated: 'PG-13',
    Released: '22 Jun 2018',
    Runtime: '128 min',
    Genre: ['Action', 'Adventure', 'Sci-Fi'],
    Director: 'J.A. Bayona',
    Writer: 'Derek Connolly, Colin Trevorrow, Michael Crichton (based on characters created by)',
    Actors: 'Chris Pratt, Bryce Dallas Howard, Rafe Spall, Justice Smith',
    Plot: "When the island's dormant volcano begins roaring to life, Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction-level event.",
    Language: 'English, Russian',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzIxMjYwNDEwN15BMl5BanBnXkFtZTgwMzk5MDI3NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNzIxMjYwNDEwN15BMl5BanBnXkFtZTgwMzk5MDI3NTM@._V1_SX300.jpg',
    imdbRating: '6.3',
    Quantity: 100,
  }, {
    Title: 'Ready Player One',
    Year: '2018',
    Rated: 'PG-13',
    Released: '29 Mar 2018',
    Runtime: '140 min',
    Genre: ['Action', 'Adventure', 'Sci-Fi'],
    Director: 'Steven Spielberg',
    Writer: 'Zak Penn (screenplay by), Ernest Cline (screenplay by), Ernest Cline (based on the novel by)',
    Actors: 'Tye Sheridan, Olivia Cooke, Ben Mendelsohn, Lena Waithe',
    Plot: 'When the creator of a virtual reality world called the OASIS dies, he releases a video in which he challenges all OASIS users to find his Easter Egg, which will give the finder his fortune.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BY2JiYTNmZTctYTQ1OC00YjU4LWEwMjYtZjkwY2Y5MDI0OTU3XkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BY2JiYTNmZTctYTQ1OC00YjU4LWEwMjYtZjkwY2Y5MDI0OTU3XkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_SX300.jpg',
    imdbRating: '7.6',
    Quantity: 100,
  }, {
    Title: 'The Strangers: Prey at Night',
    Year: '2018',
    Rated: 'R',
    Released: '09 Mar 2018',
    Runtime: '85 min',
    Genre: ['Horror'],
    Director: 'Johannes Roberts',
    Writer: 'Bryan Bertino, Ben Ketai',
    Actors: 'Christina Hendricks, Martin Henderson, Bailee Madison, Lewis Pullman',
    Plot: 'A family of four staying at a secluded mobile home park for the night are stalked and then hunted by three masked psychopaths.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTY1OTIwODgzMV5BMl5BanBnXkFtZTgwMzUyMDgzNDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTY1OTIwODgzMV5BMl5BanBnXkFtZTgwMzUyMDgzNDM@._V1_SX300.jpg',
    imdbRating: '5.2',
    Quantity: 100,
  }, {
    Title: 'The 15:17 to Paris',
    Year: '2018',
    Rated: 'PG-13',
    Released: '09 Feb 2018',
    Runtime: '94 min',
    Genre: ['Biography', 'Drama'],
    Director: 'Clint Eastwood',
    Writer: 'Dorothy Blyskal (screenplay by), Anthony Sadler (based on the book by), Alek Skarlatos (based on the book by), Spencer Stone (based on the book by), Jeffrey E. Stern (based on the book by)',
    Actors: 'Ray Corasani, Alek Skarlatos, Anthony Sadler, Spencer Stone',
    Plot: 'American Marines discover a terrorist plot on a Paris-bound train.',
    Language: 'English, French, Arabic, German, Dutch',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTY0NjUzNjYwOV5BMl5BanBnXkFtZTgwMzY1MDM0NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTY0NjUzNjYwOV5BMl5BanBnXkFtZTgwMzY1MDM0NDM@._V1_SX300.jpg',
    imdbRating: '5.1',
    Quantity: 100,
  }, {
    Title: "The Girl in the Spider's Web: A New Dragon Tattoo Story",
    Year: '2018',
    Rated: 'N/A',
    Released: '09 Nov 2018',
    Runtime: '117 min',
    Genre: ['Crime', 'Drama', 'Thriller'],
    Director: 'Fede Alvarez',
    Writer: 'Jay Basu (screenplay by), Fede Alvarez (screenplay by), Steven Knight (screenplay by), David Lagercrantz (based on the book by), Stieg Larsson (based on the characters by)',
    Actors: 'Claire Foy, Sylvia Hoeks, Lakeith Stanfield, Stephen Merchant',
    Plot: 'Young computer hacker Lisbeth Salander and journalist Mikael Blomkvist find themselves caught in a web of spies, cybercriminals and corrupt government officials.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BZWU4ZDI5OGEtOTdmZS00MmNiLWIzNjQtZGM1MGE0M2UzYTczXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BZWU4ZDI5OGEtOTdmZS00MmNiLWIzNjQtZGM1MGE0M2UzYTczXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    imdbRating: '5.8',
    Quantity: 100,
  }, {
    Title: 'Like Father',
    Year: '2018',
    Rated: 'TV-MA',
    Released: '03 Aug 2018',
    Runtime: '98 min',
    Genre: ['Comedy', 'Drama'],
    Director: 'Lauren Miller Rogen',
    Writer: 'Lauren Miller Rogen (screenplay by), Anders Bard (story by), Lauren Miller Rogen (story by)',
    Actors: 'Kristen Bell, Danielle Davenport, Kimiko Glenn, Wynter Kullman',
    Plot: "After she's left at the altar, a workaholic advertising executive ends up on her Caribbean honeymoon cruise with her estranged father.",
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTY1NDc3MzgxNV5BMl5BanBnXkFtZTgwNDc3MTQwNjM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTY1NDc3MzgxNV5BMl5BanBnXkFtZTgwNDc3MTQwNjM@._V1_SX300.jpg',
    imdbRating: '6.1',
    Quantity: 100,
  }, {
    Title: 'The Meg',
    Year: '2018',
    Rated: 'PG-13',
    Released: '10 Aug 2018',
    Runtime: '113 min',
    Genre: ['Action', 'Horror', 'Sci-Fi', 'Thriller'],
    Director: 'Jon Turteltaub',
    Writer: 'Dean Georgaris (screenplay by), Jon Hoeber (screenplay by), Erich Hoeber (screenplay by), Steve Alten (based on the novel "Meg" by)',
    Actors: 'Jason Statham, Bingbing Li, Rainn Wilson, Cliff Curtis',
    Plot: 'After escaping an attack by what he claims was a 70-foot shark, Jonas Taylor must confront his fears to save those trapped in a sunken submersible.',
    Language: 'English, Mandarin',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjg0MzA4MDE0N15BMl5BanBnXkFtZTgwMzk3MzAwNjM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjg0MzA4MDE0N15BMl5BanBnXkFtZTgwMzk3MzAwNjM@._V1_SX300.jpg',
    imdbRating: '5.9',
    Quantity: 100,
  }, {
    Title: 'Ralph Breaks the Internet',
    Year: '2018',
    Rated: 'N/A',
    Released: '21 Nov 2018',
    Runtime: '112 min',
    Genre: ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy'],
    Director: 'Phil Johnston, Rich Moore',
    Writer: 'Phil Johnston (screenplay by), Pamela Ribon (screenplay by), Rich Moore (story by), Phil Johnston (story by), Jim Reardon (story by), Pamela Ribon (story by), Josie Trinidad (story by)',
    Actors: 'John C. Reilly, Sarah Silverman, Gal Gadot, Taraji P. Henson',
    Plot: 'Six years after the events of "Wreck-It Ralph", Ralph and Vanellope, now friends, discover a wi-fi router in their arcade, leading them into a new adventure.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTYyNzEyNDAzOV5BMl5BanBnXkFtZTgwNTk3NDczNjM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTYyNzEyNDAzOV5BMl5BanBnXkFtZTgwNTk3NDczNjM@._V1_SX300.jpg',
    imdbRating: '8.4',
    Quantity: 100,
  }, {
    Title: 'Sicario: Day of the Soldado',
    Year: '2018',
    Rated: 'R',
    Released: '29 Jun 2018',
    Runtime: '122 min',
    Genre: ['Action', 'Crime', 'Drama', 'Thriller'],
    Director: 'Stefano Sollima',
    Writer: 'Taylor Sheridan',
    Actors: 'Benicio Del Toro, Josh Brolin, Isabela Moner, Jeffrey Donovan',
    Plot: 'The drug war on the U.S.-Mexico border has escalated as the cartels have begun trafficking terrorists across the US border. To fight the war, federal agent Matt Graver re-teams with the mercurial Alejandro.',
    Language: 'English, Spanish, American Sign Language',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjgyOWRhMDctZTZlNC00M2I1LWI0NDQtYzlmODdmYjY2MThiXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjgyOWRhMDctZTZlNC00M2I1LWI0NDQtYzlmODdmYjY2MThiXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_SX300.jpg',
    imdbRating: '7.2',
    Quantity: 100,
  }, {
    Title: 'Bumblebee',
    Year: '2018',
    Rated: 'N/A',
    Released: '21 Dec 2018',
    Runtime: 'N/A',
    Genre: ['Action', 'Adventure', 'Sci-Fi'],
    Director: 'Travis Knight',
    Writer: 'Christina Hodson (screenplay by), Christina Hodson (story by)',
    Actors: 'Hailee Steinfeld, Justin Theroux, Angela Bassett, Pamela Adlon',
    Plot: 'On the run in the year 1987, Bumblebee finds refuge in a junkyard in a small Californian beach town. Charlie, on the cusp of turning 18 and trying to find her place in the world, discovers Bumblebee, battle-scarred and broken.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BOTM3NzE5OTE1Nl5BMl5BanBnXkFtZTgwNzQwNjM3NjM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BOTM3NzE5OTE1Nl5BMl5BanBnXkFtZTgwNzQwNjM3NjM@._V1_SX300.jpg',
    imdbRating: 'N/A',
    Quantity: 100,
  }, {
    Title: 'Smallfoot',
    Year: '2018',
    Rated: 'PG',
    Released: '28 Sep 2018',
    Runtime: '96 min',
    Genre: ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Musical'],
    Director: 'Karey Kirkpatrick, Jason Reisig(co-director)',
    Writer: 'Karey Kirkpatrick (screenplay by), Clare Sera (screenplay by), John Requa (screen story by), Glenn Ficarra (screen story by), Karey Kirkpatrick (screen story by), Sergio Pablos (based on the book "Yeti Tracks" by), Sergio Pablos',
    Actors: 'Channing Tatum, James Corden, Zendaya, Common',
    Plot: 'A Yeti is convinced that the elusive creatures known as "humans" really do exist.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTc5NzI1NjY4MV5BMl5BanBnXkFtZTgwNDIxNTIyNDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTc5NzI1NjY4MV5BMl5BanBnXkFtZTgwNDIxNTIyNDM@._V1_SX300.jpg',
    imdbRating: '6.8',
    Quantity: 100,
  }, {
    Title: 'Peter Rabbit',
    Year: '2018',
    Rated: 'PG',
    Released: '09 Feb 2018',
    Runtime: '95 min',
    Genre: ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy'],
    Director: 'Will Gluck',
    Writer: 'Rob Lieber (screen story by), Will Gluck (screen story by), Rob Lieber (screenplay by), Will Gluck (screenplay by), Beatrix Potter (based on the characters and tales of "Peter Rabbit" by)',
    Actors: 'James Corden, Fayssal Bazzi, Domhnall Gleeson, Sia',
    Plot: "Feature adaptation of Beatrix Potter's classic tale of a rebellious rabbit trying to sneak into a farmer's vegetable garden.",
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMzI5MzZmZjItOGQzZC00NjNiLWFjMjQtMGNhY2NmNDMyNGM1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMzI5MzZmZjItOGQzZC00NjNiLWFjMjQtMGNhY2NmNDMyNGM1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    imdbRating: '6.6',
    Quantity: 100,
  }, {
    Title: 'Death Wish',
    Year: '2018',
    Rated: 'R',
    Released: '02 Mar 2018',
    Runtime: '107 min',
    Genre: ['Action', 'Crime', 'Drama', 'Thriller'],
    Director: 'Eli Roth',
    Writer: 'Joe Carnahan (screenplay by), Brian Garfield (from the novel by), Wendell Mayes (based on the 1974 motion picture by)',
    Actors: "Bruce Willis, Vincent D'Onofrio, Elisabeth Shue, Camila Morrone",
    Plot: 'Dr. Paul Kersey is an experienced trauma surgeon, a man who has spent his life saving lives. After an attack on his family, Paul embarks on his own mission for justice.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTkzNjU3MjE0MF5BMl5BanBnXkFtZTgwNTIyNDk0NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTkzNjU3MjE0MF5BMl5BanBnXkFtZTgwNTIyNDk0NDM@._V1_SX300.jpg',
    imdbRating: '6.4',
    Quantity: 100,
  }, {
    Title: 'When We First Met',
    Year: '2018',
    Rated: 'TV-14',
    Released: '09 Feb 2018',
    Runtime: '97 min',
    Genre: ['Comedy', 'Fantasy', 'Romance'],
    Director: 'Ari Sandel',
    Writer: 'John Whittington',
    Actors: 'Adam Devine, Alexandra Daddario, Shelley Hennig, Andrew Bachelor',
    Plot: 'Noah thinks he has the perfect first night with Avery, the girl of his dreams, but gets relegated to the friend zone. He spends the next three years wondering what went wrong - until he ...',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMzM1OTI4NDM4Nl5BMl5BanBnXkFtZTgwMDAwODg2NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMzM1OTI4NDM4Nl5BMl5BanBnXkFtZTgwMDAwODg2NDM@._V1_SX300.jpg',
    imdbRating: '6.4',
    Quantity: 100,
  }, {
    Title: 'Venom',
    Year: '2018',
    Rated: 'N/A',
    Released: '05 Oct 2018',
    Runtime: '112 min',
    Genre: ['Action', 'Sci-Fi'],
    Director: 'Ruben Fleischer',
    Writer: "Jeff Pinkner (screenplay by), Scott Rosenberg (screenplay by), Kelly Marcel (screenplay by), Jeff Pinkner (screen story by), Scott Rosenberg (screen story by), Todd McFarlane (Marvel's Venom Character created by), David Michelinie (Marvel's Venom Character created by)",
    Actors: 'Tom Hardy, Michelle Williams, Riz Ahmed, Scott Haze',
    Plot: 'When Eddie Brock acquires the powers of a symbiote, he will have to release his alter-ego "Venom" to save his life.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzAwNzUzNjY4MV5BMl5BanBnXkFtZTgwMTQ5MzM0NjM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNzAwNzUzNjY4MV5BMl5BanBnXkFtZTgwMTQ5MzM0NjM@._V1_SX300.jpg',
    imdbRating: '7.0',
    Quantity: 100,
  }, {
    Title: 'Christopher Robin',
    Year: '2018',
    Rated: 'PG',
    Released: '03 Aug 2018',
    Runtime: '104 min',
    Genre: ['Animation', 'Adventure', 'Comedy', 'Drama', 'Family', 'Fantasy'],
    Director: 'Marc Forster',
    Writer: 'Alex Ross Perry (screenplay by), Tom McCarthy (screenplay by), Allison Schroeder (screenplay by), Greg Brooker (story by), Mark Steven Johnson (story by), A.A. Milne (based on characters created by), Ernest Shepard (based on characters created by)',
    Actors: 'Ewan McGregor, Hayley Atwell, Bronte Carmichael, Mark Gatiss',
    Plot: 'A working-class family man, Christopher Robin, encounters his childhood friend Winnie-the-Pooh, who helps him to rediscover the joys of life.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjAzOTM2OTAyNF5BMl5BanBnXkFtZTgwNTg5ODg1NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjAzOTM2OTAyNF5BMl5BanBnXkFtZTgwNTg5ODg1NTM@._V1_SX300.jpg',
    imdbRating: '7.6',
    Quantity: 100,
  }, {
    Title: "Ocean's Eight",
    Year: '2018',
    Rated: 'PG-13',
    Released: '08 Jun 2018',
    Runtime: '110 min',
    Genre: ['Action', 'Comedy', 'Crime', 'Thriller'],
    Director: 'Gary Ross',
    Writer: 'Gary Ross (screenplay by), Olivia Milch (screenplay by), Gary Ross (story by), George Clayton Johnson (based upon characters created by), Jack Golden Russell (based upon characters created by)',
    Actors: 'Sandra Bullock, Griffin Dunne, Deidre Goodwin, Daniella Rabbani',
    Plot: "Debbie Ocean gathers an all-female crew to attempt an impossible heist at New York City's yearly Met Gala.",
    Language: 'English, Hindi, French, German, Chinese',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjAyNDEyMzc4Ml5BMl5BanBnXkFtZTgwMjEzNjM0NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjAyNDEyMzc4Ml5BMl5BanBnXkFtZTgwMjEzNjM0NTM@._V1_SX300.jpg',
    imdbRating: '6.3',
    Quantity: 100,
  }, {
    Title: 'Life of the Party',
    Year: '2018',
    Rated: 'PG-13',
    Released: '11 May 2018',
    Runtime: '105 min',
    Genre: ['Comedy'],
    Director: 'Ben Falcone',
    Writer: 'Melissa McCarthy, Ben Falcone',
    Actors: 'Melissa McCarthy, Matt Walsh, Molly Gordon, Ben Falcone',
    Plot: 'After her husband abruptly asks for a divorce, a middle-aged mother returns to college in order to complete her degree.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTkzOTk0MjYwM15BMl5BanBnXkFtZTgwNTE5ODQxNTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTkzOTk0MjYwM15BMl5BanBnXkFtZTgwNTE5ODQxNTM@._V1_SX300.jpg',
    imdbRating: '5.5',
    Quantity: 100,
  }, {
    Title: 'The Spy Who Dumped Me',
    Year: '2018',
    Rated: 'R',
    Released: '03 Aug 2018',
    Runtime: '117 min',
    Genre: ['Action', 'Adventure', 'Comedy'],
    Director: 'Susanna Fogel',
    Writer: 'Susanna Fogel, David Iserson',
    Actors: 'Justin Theroux, Blanka Györfi-Tóth, Vilma Szécsi, Mila Kunis',
    Plot: 'Audrey and Morgan are best friends who unwittingly become entangled in an international conspiracy when one of the women discovers the boyfriend who dumped her was actually a spy.',
    Language: 'English, Russian, French',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNDY1MTA0NjgyN15BMl5BanBnXkFtZTgwMTEzNDQ4NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNDY1MTA0NjgyN15BMl5BanBnXkFtZTgwMTEzNDQ4NTM@._V1_SX300.jpg',
    imdbRating: '6.1',
    Quantity: 100,
  }, {
    Title: 'Arizona',
    Year: '2018',
    Rated: 'N/A',
    Released: '24 Aug 2018',
    Runtime: '85 min',
    Genre: ['Comedy', 'Thriller'],
    Director: 'Jonathan Watson',
    Writer: 'Luke Del Tredici',
    Actors: 'Danny McBride, Rosemarie DeWitt, Lolli Sorenson, Luke Wilson',
    Plot: 'Set in the midst of the 2009 housing crisis, this darkly comedic story follows Cassie Fowler, a single mom and struggling realtor whose life goes off the rails when she witnesses a murder.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTRkNjQyMWEtN2YwYy00MzVkLWEyMTEtN2Y3MWZiOGFkZWY2XkEyXkFqcGdeQXVyMzQwMTY2Nzk@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTRkNjQyMWEtN2YwYy00MzVkLWEyMTEtN2Y3MWZiOGFkZWY2XkEyXkFqcGdeQXVyMzQwMTY2Nzk@._V1_SX300.jpg',
    imdbRating: '5.7',
    Quantity: 100,
  }, {
    Title: '12 Strong',
    Year: '2018',
    Rated: 'R',
    Released: '19 Jan 2018',
    Runtime: '130 min',
    Genre: ['Action', 'Drama', 'History', 'War'],
    Director: 'Nicolai Fuglsig',
    Writer: 'Ted Tally, Peter Craig, Doug Stanton (based on the book,  "Horse Soldiers" by)',
    Actors: 'Chris Hemsworth, Michael Shannon, Michael Peña, Navid Negahban',
    Plot: '12 Strong tells the story of the first Special Forces team deployed to Afghanistan after 9/11; under the leadership of a new captain, the team must work with an Afghan warlord to take down the Taliban.',
    Language: 'English, Dari, Russian, Spanish, Uzbek',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNTEzMjk3NzkxMV5BMl5BanBnXkFtZTgwNjY2NDczNDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNTEzMjk3NzkxMV5BMl5BanBnXkFtZTgwNjY2NDczNDM@._V1_SX300.jpg',
    imdbRating: '6.6',
    Quantity: 100,
  }, {
    Title: 'SuperFly',
    Year: '2018',
    Rated: 'R',
    Released: '13 Jun 2018',
    Runtime: '116 min',
    Genre: ['Action', 'Crime', 'Thriller'],
    Director: 'Director X.',
    Writer: 'Alex Tse (screenplay by)',
    Actors: 'Trevor Jackson, Jason Mitchell, Michael Kenneth Williams, Lex Scott Davis',
    Plot: 'With retirement on his mind, a successful young drug dealer sets up one last big job, while dealing with trigger-happy colleagues and the police.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMWU1Yzc0ZDUtNGFlZC00ZTFkLWIxMTEtZTQ5ZTliYzIxZWI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMWU1Yzc0ZDUtNGFlZC00ZTFkLWIxMTEtZTQ5ZTliYzIxZWI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    imdbRating: '5.1',
    Quantity: 100,
  }, {
    Title: 'Creed II',
    Year: '2018',
    Rated: 'N/A',
    Released: '21 Nov 2018',
    Runtime: '130 min',
    Genre: ['Drama', 'Sport'],
    Director: 'Steven Caple Jr.',
    Writer: 'Cheo Hodari Coker (story by), Ryan Coogler (characters), Sascha Penn (story by), Sylvester Stallone (screenplay by), Juel Taylor (screenplay by), Juel Taylor',
    Actors: 'Dolph Lundgren, Tessa Thompson, Sylvester Stallone, Michael B. Jordan',
    Plot: 'Under the tutelage of Rocky Balboa, light heavyweight contender Adonis Creed faces off against Viktor Drago, the son of Ivan Drago.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjA3MTAxNDkxMl5BMl5BanBnXkFtZTgwMzI4MzE0NjM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjA3MTAxNDkxMl5BMl5BanBnXkFtZTgwMzI4MzE0NjM@._V1_SX300.jpg',
    imdbRating: '8.7',
    Quantity: 100,
  }, {
    Title: 'A Quiet Place',
    Year: '2018',
    Rated: 'PG-13',
    Released: '06 Apr 2018',
    Runtime: '90 min',
    Genre: ['Drama', 'Horror', 'Mystery', 'Sci-Fi', 'Thriller'],
    Director: 'John Krasinski',
    Writer: 'Bryan Woods (screenplay by), Scott Beck (screenplay by), John Krasinski (screenplay by), Bryan Woods (story by), Scott Beck (story by)',
    Actors: 'Emily Blunt, John Krasinski, Millicent Simmonds, Noah Jupe',
    Plot: 'In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.',
    Language: 'English, American Sign Language',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_SX300.jpg',
    imdbRating: '7.6',
    Quantity: 100,
  }, {
    Title: 'Mary Poppins Returns',
    Year: '2018',
    Rated: 'N/A',
    Released: '19 Dec 2018',
    Runtime: 'N/A',
    Genre: ['Family', 'Fantasy', 'Musical'],
    Director: 'Rob Marshall',
    Writer: 'David Magee (screenplay by), David Magee (screen story by), Rob Marshall (screen story by), John DeLuca (screen story by), P.L. Travers (based upon the "Mary Poppins" stories by)',
    Actors: 'Emily Blunt, Colin Firth, Meryl Streep, Emily Mortimer',
    Plot: "In Depression-era London, a now-grown Jane and Michael Banks, along with Michael's three children, are visited by the enigmatic Mary Poppins following a personal loss. Through her unique ...",
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTY4MjYzOTc1NF5BMl5BanBnXkFtZTgwMTkyNzU5NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTY4MjYzOTc1NF5BMl5BanBnXkFtZTgwMTkyNzU5NDM@._V1_SX300.jpg',
    imdbRating: 'N/A',
    Quantity: 100,
  }, {
    Title: 'Extinction',
    Year: '2018',
    Rated: 'TV-MA',
    Released: '27 Jul 2018',
    Runtime: '95 min',
    Genre: ['Action', 'Drama', 'Sci-Fi', 'Thriller'],
    Director: 'Ben Young',
    Writer: 'Spenser Cohen (screenplay by), Brad Kane (screenplay by), Spenser Cohen (story by)',
    Actors: 'Michael Peña, Lizzy Caplan, Amelia Crouch, Erica Tremblay',
    Plot: 'A father has a recurring dream of losing his family. His nightmare turns into reality when the planet is invaded by a force bent on destruction. Fighting for their lives, he comes to realize an unknown strength to keep them safe from harm.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTU5OTYzMzcwOF5BMl5BanBnXkFtZTgwNTkzMzk4NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTU5OTYzMzcwOF5BMl5BanBnXkFtZTgwNTkzMzk4NTM@._V1_SX300.jpg',
    imdbRating: '5.8',
    Quantity: 100,
  }, {
    Title: 'Rampage',
    Year: '2018',
    Rated: 'PG-13',
    Released: '13 Apr 2018',
    Runtime: '107 min',
    Genre: ['Action', 'Adventure', 'Sci-Fi'],
    Director: 'Brad Peyton',
    Writer: 'Ryan Engle (screenplay by), Carlton Cuse (screenplay by), Ryan J. Condal (screenplay by), Adam Sztykiel (screenplay by), Ryan Engle (story by)',
    Actors: 'Dwayne Johnson, Naomie Harris, Malin Akerman, Jeffrey Dean Morgan',
    Plot: 'When three different animals become infected with a dangerous pathogen, a primatologist and a geneticist team up to stop them from destroying Chicago.',
    Language: 'English, American Sign Language',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNDA1NjA3ODU3OV5BMl5BanBnXkFtZTgwOTg3MTIwNTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNDA1NjA3ODU3OV5BMl5BanBnXkFtZTgwOTg3MTIwNTM@._V1_SX300.jpg',
    imdbRating: '6.2',
    Quantity: 100,
  }, {
    Title: 'Terminal',
    Year: '2018',
    Rated: 'NOT RATED',
    Released: '11 May 2018',
    Runtime: '95 min',
    Genre: ['Crime', 'Drama', 'Thriller'],
    Director: 'Vaughn Stein',
    Writer: 'Vaughn Stein',
    Actors: 'Margot Robbie, Simon Pegg, Dexter Fletcher, Mike Myers',
    Plot: 'In the dark heart of a sprawling, anonymous city, TERMINAL follows the twisting tales of two assassins carrying out a sinister mission, a teacher battling a fatal illness, an enigmatic ...',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYmEzOGVmNWQtZDBiMC00OTk4LTg3OWQtMzc2MzgxNjlkY2JjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BYmEzOGVmNWQtZDBiMC00OTk4LTg3OWQtMzc2MzgxNjlkY2JjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    imdbRating: '5.3',
    Quantity: 100,
  }, {
    Title: 'A Star Is Born',
    Year: '2018',
    Rated: 'R',
    Released: '05 Oct 2018',
    Runtime: '136 min',
    Genre: ['Drama', 'Music', 'Romance'],
    Director: 'Bradley Cooper',
    Writer: 'Eric Roth (screenplay by), Bradley Cooper (screenplay by), Will Fetters (screenplay by), Moss Hart (based on the 1954 screenplay by), John Gregory Dunne (based on the 1976 screenplay by), Joan Didion (based on the 1976 screenplay by), Frank Pierson (based on the 1976 screenplay by), William A. Wellman (based on a story by), Robert Carson (based on a story by)',
    Actors: 'Lady Gaga, Bradley Cooper, Sam Elliott, Andrew Dice Clay',
    Plot: 'A musician helps a young singer find fame, even as age and alcoholism send his own career into a downward spiral.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjE3MDQ0MTA3M15BMl5BanBnXkFtZTgwMDMwNDY2NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjE3MDQ0MTA3M15BMl5BanBnXkFtZTgwMDMwNDY2NTM@._V1_SX300.jpg',
    imdbRating: '8.2',
    Quantity: 100,
  }, {
    Title: 'Winchester',
    Year: '2018',
    Rated: 'PG-13',
    Released: '02 Feb 2018',
    Runtime: '99 min',
    Genre: ['Biography', 'Fantasy', 'Horror', 'Mystery', 'Thriller'],
    Director: 'Michael Spierig, Peter Spierig',
    Writer: 'Tom Vaughan, Michael Spierig, Peter Spierig',
    Actors: "Helen Mirren, Sarah Snook, Finn Scicluna-O'Prey, Jason Clarke",
    Plot: 'Ensconced in her sprawling California mansion, eccentric firearm heiress Sarah Winchester believes she is haunted by the souls of people killed by the Winchester repeating rifle.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjI2OWE5OGItMTE4Yi00ZmIzLThjZDctNTU1OTMxMTc3Yjg4XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjI2OWE5OGItMTE4Yi00ZmIzLThjZDctNTU1OTMxMTc3Yjg4XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg',
    imdbRating: '5.4',
    Quantity: 100,
  }, {
    Title: 'The Commuter',
    Year: '2018',
    Rated: 'PG-13',
    Released: '12 Jan 2018',
    Runtime: '105 min',
    Genre: ['Action', 'Crime', 'Drama', 'Mystery', 'Thriller'],
    Director: 'Jaume Collet-Serra',
    Writer: 'Byron Willinger (story by), Philip de Blasi (story by), Byron Willinger (screenplay by), Philip de Blasi (screenplay by), Ryan Engle (screenplay by)',
    Actors: 'Liam Neeson, Vera Farmiga, Patrick Wilson, Jonathan Banks',
    Plot: 'An Insurance Salesman/Ex-Cop is caught up in a criminal conspiracy during his daily commute home.',
    Language: 'English, Spanish',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTc0NDg1MjI4OV5BMl5BanBnXkFtZTgwMDIwMTEwNDI@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTc0NDg1MjI4OV5BMl5BanBnXkFtZTgwMDIwMTEwNDI@._V1_SX300.jpg',
    imdbRating: '6.3',
    Quantity: 100,
  }, {
    Title: 'Robin Hood',
    Year: '2018',
    Rated: 'N/A',
    Released: '06 Jun 2018',
    Runtime: 'N/A',
    Genre: ['Adventure'],
    Director: 'Diana Brooks',
    Writer: 'N/A',
    Actors: 'Joseph Steyne, Andrew Swift, Jamie B. Chambers, Victoria Gibson',
    Plot: 'Behind the legend. The story of dark magic, and power struggles.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYzEyY2JjMzUtZWI2ZC00N2VhLTg5MjctYzExYmM1ZTQ3ZjEzXkEyXkFqcGdeQXVyNjQwODk0OTA@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BYzEyY2JjMzUtZWI2ZC00N2VhLTg5MjctYzExYmM1ZTQ3ZjEzXkEyXkFqcGdeQXVyNjQwODk0OTA@._V1_SX300.jpg',
    imdbRating: 'N/A',
    Quantity: 100,
  }, {
    Title: 'Ant-Man and the Wasp',
    Year: '2018',
    Rated: 'PG-13',
    Released: '06 Jul 2018',
    Runtime: '118 min',
    Genre: ['Action', 'Adventure', 'Comedy', 'Sci-Fi'],
    Director: 'Peyton Reed',
    Writer: 'Chris McKenna, Erik Sommers, Paul Rudd, Andrew Barrer, Gabriel Ferrari, Stan Lee (based on the Marvel Comics by), Larry Lieber (based on the Marvel Comics by), Jack Kirby (based on the Marvel Comics by)',
    Actors: 'Paul Rudd, Evangeline Lilly, Michael Peña, Walton Goggins',
    Plot: 'As Scott Lang balances being both a Super Hero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYjcyYTk0N2YtMzc4ZC00Y2E0LWFkNDgtNjE1MzZmMGE1YjY1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BYjcyYTk0N2YtMzc4ZC00Y2E0LWFkNDgtNjE1MzZmMGE1YjY1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    imdbRating: '7.2',
    Quantity: 100,
  }, {
    Title: 'Incredibles 2',
    Year: '2018',
    Rated: 'PG',
    Released: '15 Jun 2018',
    Runtime: '118 min',
    Genre: ['Animation', 'Action', 'Adventure', 'Comedy', 'Family', 'Sci-Fi'],
    Director: 'Brad Bird',
    Writer: 'Brad Bird',
    Actors: 'Craig T. Nelson, Holly Hunter, Sarah Vowell, Huck Milner',
    Plot: 'Bob Parr (Mr. Incredible) is left to care for the kids while Helen (Elastigirl) is out saving the world.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTEzNzY0OTg0NTdeQTJeQWpwZ15BbWU4MDU3OTg3MjUz._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTEzNzY0OTg0NTdeQTJeQWpwZ15BbWU4MDU3OTg3MjUz._V1_SX300.jpg',
    imdbRating: '8.0',
    Quantity: 100,
  }, {
    Title: 'Fantastic Beasts: The Crimes of Grindelwald',
    Year: '2018',
    Rated: 'N/A',
    Released: '16 Nov 2018',
    Runtime: '134 min',
    Genre: ['Adventure', 'Family', 'Fantasy'],
    Director: 'David Yates',
    Writer: 'J.K. Rowling, J.K. Rowling (based upon characters created by)',
    Actors: 'Johnny Depp, Kevin Guthrie, Carmen Ejogo, Wolf Roth',
    Plot: "The second installment of the \"Fantastic Beasts\" series set in J.K. Rowling's Wizarding World featuring the adventures of magizoologist Newt Scamander.",
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BZjFiMGUzMTAtNDAwMC00ZjRhLTk0OTUtMmJiMzM5ZmVjODQxXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BZjFiMGUzMTAtNDAwMC00ZjRhLTk0OTUtMmJiMzM5ZmVjODQxXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
    imdbRating: '7.4',
    Quantity: 100,
  }, {
    Title: 'A Wrinkle in Time',
    Year: '2018',
    Rated: 'PG',
    Released: '09 Mar 2018',
    Runtime: '109 min',
    Genre: ['Adventure', 'Family', 'Fantasy', 'Sci-Fi'],
    Director: 'Ava DuVernay',
    Writer: "Jennifer Lee (screenplay by), Jeff Stockwell (screenplay by), Madeleine L'Engle (based upon the novel by)",
    Actors: 'Storm Reid, Oprah Winfrey, Reese Witherspoon, Mindy Kaling',
    Plot: 'After the disappearance of her scientist father, three peculiar beings send Meg, her brother, and her friend to space in order to find him.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjMxNjQ5MTI3MV5BMl5BanBnXkFtZTgwMjQ2MTAyNDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjMxNjQ5MTI3MV5BMl5BanBnXkFtZTgwMjQ2MTAyNDM@._V1_SX300.jpg',
    imdbRating: '4.2',
    Quantity: 100,
  }, {
    Title: 'Insidious: The Last Key',
    Year: '2018',
    Rated: 'PG-13',
    Released: '05 Jan 2018',
    Runtime: '103 min',
    Genre: ['Horror', 'Mystery', 'Thriller'],
    Director: 'Adam Robitel',
    Writer: 'Leigh Whannell, Leigh Whannell (based on characters created by)',
    Actors: 'Lin Shaye, Leigh Whannell, Angus Sampson, Kirk Acevedo',
    Plot: 'Parapsychologist Dr. Elise Rainier faces her most fearsome and personal haunting yet, as she is drawn back to her ghostly childhood home, where the terror began.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTUxODU0NjQ2Nl5BMl5BanBnXkFtZTgwMTc4NDQ0MzI@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTUxODU0NjQ2Nl5BMl5BanBnXkFtZTgwMTc4NDQ0MzI@._V1_SX300.jpg',
    imdbRating: '5.7',
    Quantity: 100,
  }, {
    Title: 'The Nutcracker and the Four Realms',
    Year: '2018',
    Rated: 'N/A',
    Released: '02 Nov 2018',
    Runtime: '99 min',
    Genre: ['Adventure', 'Family', 'Fantasy'],
    Director: 'Lasse Hallström, Joe Johnston',
    Writer: 'Ashleigh Powell (screen story by), Ashleigh Powell (screenplay by), E.T.A. Hoffmann (suggested by the short story "The Nutcracker and the Mouse King" written by), Marius Petipa (suggested by the "Nutcracker Ballet" by)',
    Actors: 'Mackenzie Foy, Tom Sweet, Meera Syal, Ellie Bamber',
    Plot: 'A young girl is transported into a magical world of gingerbread soldiers and an army of mice.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTgzOTc0NTE3Nl5BMl5BanBnXkFtZTgwODY4MDgwNjM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTgzOTc0NTE3Nl5BMl5BanBnXkFtZTgwODY4MDgwNjM@._V1_SX300.jpg',
    imdbRating: '5.6',
    Quantity: 100,
  }, {
    Title: 'Blockers',
    Year: '2018',
    Rated: 'R',
    Released: '06 Apr 2018',
    Runtime: '102 min',
    Genre: ['Comedy'],
    Director: 'Kay Cannon',
    Writer: 'Brian Kehoe, Jim Kehoe',
    Actors: 'Leslie Mann, John Cena, Ike Barinholtz, Kathryn Newton',
    Plot: 'Three parents try to stop their daughters from losing their virginity on prom night.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjE0ODIzNjkzMl5BMl5BanBnXkFtZTgwODQ3MzU4NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjE0ODIzNjkzMl5BMl5BanBnXkFtZTgwODQ3MzU4NDM@._V1_SX300.jpg',
    imdbRating: '6.2',
    Quantity: 100,
  }, {
    Title: 'I Feel Pretty',
    Year: '2018',
    Rated: 'PG-13',
    Released: '20 Apr 2018',
    Runtime: '110 min',
    Genre: ['Comedy'],
    Director: 'Abby Kohn, Marc Silverstein',
    Writer: 'Abby Kohn, Marc Silverstein',
    Actors: 'Amy Schumer, Michelle Williams, Tom Hopper, Rory Scovel',
    Plot: 'A woman struggling with insecurity wakes from a fall believing she is the most beautiful and capable woman on the planet. Her new confidence empowers her to live fearlessly, but what happens when she realizes her appearance never changed?',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMGI3ZDRjZTQtMTMyYy00NGI4LWI2MjktNzMyMjg0NjQ2NTY0XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMGI3ZDRjZTQtMTMyYy00NGI4LWI2MjktNzMyMjg0NjQ2NTY0XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    imdbRating: '5.3',
    Quantity: 100,
  }, {
    Title: 'Peppermint',
    Year: '2018',
    Rated: 'R',
    Released: '07 Sep 2018',
    Runtime: '101 min',
    Genre: ['Action', 'Drama', 'Thriller'],
    Director: 'Pierre Morel',
    Writer: 'Chad St. John',
    Actors: 'Jennifer Garner, John Gallagher Jr., John Ortiz, Juan Pablo Raba',
    Plot: 'Five years after her husband and daughter are killed in a senseless act of violence, a woman comes back from self-imposed exile to seek revenge against those responsible and the system that let them go free.',
    Language: 'English, Spanish',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNWVlMjQ3MjItOWE3YS00YTYwLWE0ZDMtZWMyZWY1NzkxNWIwXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNWVlMjQ3MjItOWE3YS00YTYwLWE0ZDMtZWMyZWY1NzkxNWIwXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    imdbRating: '6.6',
    Quantity: 100,
  }, {
    Title: 'Samson',
    Year: '2018',
    Rated: 'PG-13',
    Released: '16 Feb 2018',
    Runtime: '110 min',
    Genre: ['Action', 'Drama'],
    Director: 'Bruce Macdonald, Gabriel Sabloff(co-director)',
    Writer: 'Jason Baumgardner, Galen Gilbert, Timothy Ratajczak, Zach Smith',
    Actors: 'Jackson Rathbone, Billy Zane, Taylor James, Rutger Hauer',
    Plot: 'After losing the love of his life to a cruel Philistine prince, a young Hebrew with Supernatural strength defends his people, sacrificing everything to avenge his love, his people, and his God.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYThiMjg4ZDAtNjk5ZS00ZTUxLThmM2ItMGI0ZTE1NjRhNWNmXkEyXkFqcGdeQXVyNTQ3MjE4NTU@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BYThiMjg4ZDAtNjk5ZS00ZTUxLThmM2ItMGI0ZTE1NjRhNWNmXkEyXkFqcGdeQXVyNTQ3MjE4NTU@._V1_SX300.jpg',
    imdbRating: '4.3',
    Quantity: 100,
  }, {
    Title: 'Skyscraper',
    Year: '2018',
    Rated: 'PG-13',
    Released: '13 Jul 2018',
    Runtime: '102 min',
    Genre: ['Action', 'Thriller'],
    Director: 'Rawson Marshall Thurber',
    Writer: 'Rawson Marshall Thurber',
    Actors: 'Dwayne Johnson, Neve Campbell, Chin Han, Roland Møller',
    Plot: 'A security expert must infiltrate a burning skyscraper, 225 stories above ground, when his family are trapped inside by criminals.',
    Language: 'English, Cantonese, Mandarin',
    Poster: 'https://m.media-amazon.com/images/M/MV5BOGM3MzQwYzItNDA1Ny00MzIyLTg5Y2QtYTAwMzNmMDU2ZDgxXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BOGM3MzQwYzItNDA1Ny00MzIyLTg5Y2QtYTAwMzNmMDU2ZDgxXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg',
    imdbRating: '5.9',
    Quantity: 100,
  }, {
    Title: 'Black Panther',
    Year: '2018',
    Rated: 'PG-13',
    Released: '16 Feb 2018',
    Runtime: '134 min',
    Genre: ['Action', 'Adventure', 'Sci-Fi'],
    Director: 'Ryan Coogler',
    Writer: 'Ryan Coogler, Joe Robert Cole, Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel Comics by)',
    Actors: "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o, Danai Gurira",
    Plot: "After the death of his father, Prince T'Challa ascends to the throne of the small African country of Wakanda. T'Challa is also Black Panther, superhero. Now not only must he govern his country but defeat a dangerous adversary.",
    Language: 'Swahili, Nama, English, Xhosa, Korean',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg',
    imdbRating: '7.4',
    Quantity: 100,
  }, {
    Title: 'Ibiza',
    Year: '2018',
    Rated: 'TV-MA',
    Released: '25 May 2018',
    Runtime: '94 min',
    Genre: ['Comedy', 'Romance'],
    Director: 'Alex Richanbach',
    Writer: 'Lauryn Kahn',
    Actors: 'Gwen Elizabeth Duchon, Gillian Jacobs, Michaela Watkins, Phoebe Robinson',
    Plot: 'A young American woman and her two best friends seek out a hot DJ in Spain.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTczMTA5ODMxOV5BMl5BanBnXkFtZTgwNTgwNDkzNTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTczMTA5ODMxOV5BMl5BanBnXkFtZTgwNTgwNDkzNTM@._V1_SX300.jpg',
    imdbRating: '5.2',
    Quantity: 100,
  }, {
    Title: 'The Hurricane Heist',
    Year: '2018',
    Rated: 'PG-13',
    Released: '09 Mar 2018',
    Runtime: '103 min',
    Genre: ['Action', 'Crime', 'Thriller'],
    Director: 'Rob Cohen',
    Writer: 'Scott Windhauser (screenplay by), Jeff Dixon (screenplay by), Anthony Fingleton (story by), Carlos Davis (story by)',
    Actors: 'Toby Kebbell, Maggie Grace, Ryan Kwanten, Ralph Ineson',
    Plot: 'Thieves attempt a massive heist against the U.S. Treasury as a Category 5 hurricane approaches one of its Mint facilities.',
    Language: 'American Sign Language, English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMzg3Y2MyNjgtMzk4ZS00OTU3LWEwZmMtN2Y0NTdlZjU0NGFiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMzg3Y2MyNjgtMzk4ZS00OTU3LWEwZmMtN2Y0NTdlZjU0NGFiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    imdbRating: '5.0',
    Quantity: 100,
  }, {
    Title: 'Halloween',
    Year: '2018',
    Rated: 'N/A',
    Released: '19 Oct 2018',
    Runtime: '106 min',
    Genre: ['Horror', 'Mystery', 'Thriller'],
    Director: 'David Gordon Green',
    Writer: 'David Gordon Green (screenplay), Danny McBride (screenplay), Jeff Fradley (screenplay), John Carpenter (characters), Debra Hill (characters)',
    Actors: 'Jamie Lee Curtis, Judy Greer, Andi Matichak, James Jude Courtney',
    Plot: 'Laurie Strode confronts her long-time foe Michael Myers, the masked figure who has haunted her since she narrowly escaped his killing spree on Halloween night four decades ago.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMmMzNjJhYjUtNzFkZi00MWQ4LWJiMDEtYWM0NTAzNGZjMTI3XkEyXkFqcGdeQXVyOTE2OTMwNDk@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMmMzNjJhYjUtNzFkZi00MWQ4LWJiMDEtYWM0NTAzNGZjMTI3XkEyXkFqcGdeQXVyOTE2OTMwNDk@._V1_SX300.jpg',
    imdbRating: '7.2',
    Quantity: 100,
  }, {
    Title: 'The Equalizer 2',
    Year: '2018',
    Rated: 'R',
    Released: '20 Jul 2018',
    Runtime: '121 min',
    Genre: ['Action', 'Crime', 'Thriller'],
    Director: 'Antoine Fuqua',
    Writer: 'Richard Wenk, Michael Sloan (based on the television series created by), Richard Lindheim (based on the television series created by)',
    Actors: 'Denzel Washington, Pedro Pascal, Ashton Sanders, Orson Bean',
    Plot: 'Robert McCall serves an unflinching justice for the exploited and oppressed, but how far will he go when that is someone he loves?',
    Language: 'English, French, Turkish, Hebrew',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTU2OTYzODQyMF5BMl5BanBnXkFtZTgwNjU3Njk5NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTU2OTYzODQyMF5BMl5BanBnXkFtZTgwNjU3Njk5NTM@._V1_SX300.jpg',
    imdbRating: '6.9',
    Quantity: 100,
  }, {
    Title: 'Upgrade',
    Year: '2018',
    Rated: 'R',
    Released: '01 Jun 2018',
    Runtime: '100 min',
    Genre: ['Action', 'Horror', 'Sci-Fi', 'Thriller'],
    Director: 'Leigh Whannell',
    Writer: 'Leigh Whannell',
    Actors: 'Logan Marshall-Green, Melanie Vallejo, Steve Danielsen, Abby Craden',
    Plot: 'Set in the near-future, technology controls nearly all aspects of life. But when Grey, a self-identified technophobe, has his world turned upside down, his only hope for revenge is an experimental computer chip implant called Stem.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjI0NzcyMjM5Ml5BMl5BanBnXkFtZTgwMzk2NzAyNTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMjI0NzcyMjM5Ml5BMl5BanBnXkFtZTgwMzk2NzAyNTM@._V1_SX300.jpg',
    imdbRating: '7.6',
    Quantity: 100,
  }, {
    Title: 'Mission: Impossible - Fallout',
    Year: '2018',
    Rated: 'PG-13',
    Released: '27 Jul 2018',
    Runtime: '147 min',
    Genre: ['Action', 'Adventure', 'Thriller'],
    Director: 'Christopher McQuarrie',
    Writer: 'Christopher McQuarrie, Bruce Geller (based on the television series created by)',
    Actors: 'Tom Cruise, Henry Cavill, Ving Rhames, Simon Pegg',
    Plot: 'Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.',
    Language: 'English, French',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTk3NDY5MTU0NV5BMl5BanBnXkFtZTgwNDI3MDE1NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTk3NDY5MTU0NV5BMl5BanBnXkFtZTgwNDI3MDE1NTM@._V1_SX300.jpg',
    imdbRating: '8.0',
    Quantity: 100,
  }, {
    Title: 'Annihilation',
    Year: '2018',
    Rated: 'R',
    Released: '23 Feb 2018',
    Runtime: '115 min',
    Genre: ['Adventure', 'Drama', 'Horror', 'Mystery', 'Sci-Fi', 'Thriller'],
    Director: 'Alex Garland',
    Writer: 'Alex Garland (written for the screen by), Jeff VanderMeer (based on the novel by)',
    Actors: 'Natalie Portman, Benedict Wong, Sonoya Mizuno, David Gyasi',
    Plot: "A biologist signs up for a dangerous, secret expedition into a mysterious zone where the laws of nature don't apply.",
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTk2Mjc2NzYxNl5BMl5BanBnXkFtZTgwMTA2OTA1NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTk2Mjc2NzYxNl5BMl5BanBnXkFtZTgwMTA2OTA1NDM@._V1_SX300.jpg',
    imdbRating: '6.9',
    Quantity: 100,
  }, {
    Title: 'The House with a Clock in Its Walls',
    Year: '2018',
    Rated: 'N/A',
    Released: '21 Sep 2018',
    Runtime: '105 min',
    Genre: ['Comedy', 'Family', 'Fantasy', 'Horror', 'Mystery', 'Sci-Fi', 'Thriller'],
    Director: 'Eli Roth',
    Writer: 'Eric Kripke (screenplay by), John Bellairs (based on the novel by)',
    Actors: 'Jack Black, Cate Blanchett, Owen Vaccaro, Kyle MacLachlan',
    Plot: 'A young orphan named Lewis Barnavelt aids his magical uncle in locating a clock with the power to bring about the end of the world.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTk1MzM1ODEwOV5BMl5BanBnXkFtZTgwMTE0OTA4NTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTk1MzM1ODEwOV5BMl5BanBnXkFtZTgwMTE0OTA4NTM@._V1_SX300.jpg',
    imdbRating: '6.2',
    Quantity: 100,
  }, {
    Title: 'Night School',
    Year: '2018',
    Rated: 'PG-13',
    Released: '28 Sep 2018',
    Runtime: '111 min',
    Genre: ['Comedy'],
    Director: 'Malcolm D. Lee',
    Writer: 'Kevin Hart, Harry Ratchford, Joey Wells, Matthew Kellard, Nicholas Stoller, John Hamburg',
    Actors: 'Tiffany Haddish, Kevin Hart, Keith David, Mary Lynn Rajskub',
    Plot: "A group of troublemakers are forced to attend night school in hope that they'll pass the GED exam to finish high school.",
    Language: 'English, French, Spanish',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYzEyYzg5N2YtZmYzZC00OTg0LWE3ZmYtNDZhMGFkOTBjOTYxXkEyXkFqcGdeQXVyNDg2MjUxNjM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BYzEyYzg5N2YtZmYzZC00OTg0LWE3ZmYtNDZhMGFkOTBjOTYxXkEyXkFqcGdeQXVyNDg2MjUxNjM@._V1_SX300.jpg',
    imdbRating: '5.5',
    Quantity: 100,
  }, {
    Title: 'The First Purge',
    Year: '2018',
    Rated: 'R',
    Released: '04 Jul 2018',
    Runtime: '98 min',
    Genre: ['Action', 'Horror', 'Sci-Fi', 'Thriller'],
    Director: 'Gerard McMurray',
    Writer: 'James DeMonaco',
    Actors: "Y'lan Noel, Lex Scott Davis, Joivan Wade, Mugga",
    Plot: "America's third political party, the New Founding Fathers of America, comes to power and conducts an experiment: no laws for 12 hours on Staten Island. No one has to stay on the island, but $5,000 is given to anyone who does.",
    Language: 'Spanish, English, French',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYmVjMWJhMTYtMzUxMC00ODdhLTk3YzMtZDFhNGUyOGFhYTY0XkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BYmVjMWJhMTYtMzUxMC00ODdhLTk3YzMtZDFhNGUyOGFhYTY0XkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg',
    imdbRating: '5.1',
    Quantity: 100,
  }, {
    Title: 'Sherlock Gnomes',
    Year: '2018',
    Rated: 'PG',
    Released: '23 Mar 2018',
    Runtime: '86 min',
    Genre: ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Mystery', 'Romance'],
    Director: 'John Stevenson',
    Writer: 'Ben Zazove (screenplay by), Andy Riley (story by), Kevin Cecil (story by), Emily Cook (story by), Kathy Greenberg (story by), Rob Sprackling (based on characters by), Johnny Smith (based on characters by), Andy Riley (based on characters by), Kevin Cecil (based on characters by), Kelly Asbury (based on characters by), Steve Hamilton Shaw',
    Actors: 'Kelly Asbury, Mary J. Blige, Emily Blunt, Julio Bonet',
    Plot: 'Garden gnomes, Gnomeo & Juliet, recruit renowned detective Sherlock Gnomes to investigate the mysterious disappearance of other garden ornaments.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTk4NzU3NzU2NV5BMl5BanBnXkFtZTgwNDc4NTI3NDM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BMTk4NzU3NzU2NV5BMl5BanBnXkFtZTgwNDc4NTI3NDM@._V1_SX300.jpg',
    imdbRating: '5.0',
    Quantity: 100,
  }, {
    Title: 'Tomb Raider',
    Year: '2018',
    Rated: 'PG-13',
    Released: '16 Mar 2018',
    Runtime: '118 min',
    Genre: ['Action', 'Adventure', 'Fantasy', 'Thriller'],
    Director: 'Roar Uthaug',
    Writer: 'Geneva Robertson-Dworet (screenplay by), Alastair Siddons (screenplay by), Evan Daugherty (story by), Geneva Robertson-Dworet (story by)',
    Actors: 'Alicia Vikander, Dominic West, Walton Goggins, Daniel Wu',
    Plot: 'Lara Croft, the fiercely independent daughter of a missing adventurer, must push herself beyond her limits when she discovers the island where her father disappeared.',
    Language: 'English, Cantonese, Hindi',
    Poster: 'https://m.media-amazon.com/images/M/MV5BOTY4NDcyZGQtYmVlNy00ODgwLTljYTMtYzQ2OTE3NDhjODMwXkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BOTY4NDcyZGQtYmVlNy00ODgwLTljYTMtYzQ2OTE3NDhjODMwXkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_SX300.jpg',
    imdbRating: '6.4',
    Quantity: 100,
  }, {
    Title: 'Tag',
    Year: '2018',
    Rated: 'R',
    Released: '15 Jun 2018',
    Runtime: '100 min',
    Genre: ['Comedy'],
    Director: 'Jeff Tomsic',
    Writer: 'Rob McKittrick (screenplay by), Mark Steilen (screenplay by), Mark Steilen (screen story by), Russell Adams (based on the Wall Street Journal article entitled "It Takes Planning,  Caution to Avoid Being It" by)',
    Actors: 'Ed Helms, Lil Rel Howery, Jon Hamm, Annabelle Wallis',
    Plot: 'A small group of former classmates organize an elaborate, annual game of tag that requires some to travel all over the country.',
    Language: 'English',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzk4NDM3NjkwNF5BMl5BanBnXkFtZTgwNTk5MzkzNTM@._V1_SX300.jpg',
    HomePoster: 'https://m.media-amazon.com/images/M/MV5BNzk4NDM3NjkwNF5BMl5BanBnXkFtZTgwNTk5MzkzNTM@._V1_SX300.jpg',
    imdbRating: '6.6',
    Quantity: 100,
  },
];
/**
 * Initialize the Stuff collection if empty with seed data.
 */
/*
function getCategory (movie) {
  //     log.info(movie.Title);
  const genre = JSON.stringify(movie.Genre);
  if (genre.includes('Drama')) {
    if (dramaLim > 0) {
      log.info(`drama: ${movie.Title}`);
      Drama.insert(movie);
      dramaLim--;
    }
  }
  if (genre.includes('Action')) {
    if (actionLim > 0) {
      log.info(`action: ${movie.Title}`);
      Action.insert(movie);
      actionLim--;
    }
  }
  if (genre.includes('Horror')) {
    if (horrorLim > 0) {
      log.info(`horror: ${movie.Title}`);
      Horror.insert(movie);
      horrorLim--;
    }
  }
}
*/
if (Stuff.find().count() === 0) {
  _.each(stuffSeeds, function seedStuffs(stuff) {
    Stuff.insert(stuff);
  });
}
Meteor.startup(function () {
  if (Movie.find().count() <= 10) {
    _.each(movieList, function seedMovies(movie) {
      //     log.info(movie.Title);
      Movie.insert(movie);
//      getCategory(movie);
    });
  }
});

Meteor.methods({
  quantUpdate(quant) {
    console.log(quant);
    Movie.update({ _id: Meteor.userId }, { $set: { Quantity: quant } });
  },
});
